#ifndef ENABLE_DEFINES
#define ENABLE_DEFINES
/* #undef ELASTICITY */
/* #undef BREAKDOWNS_CONTROLLER */
/* #undef BREAKDOWNS_VINETALK */
/* #undef DATA_TRANSFER */
/* #undef REDUCTION_UNITS_FROM_EXEC_TIME */
/* #undef POWER_TIMER */
#endif
